FROM node:18-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --force --no-audit --no-fund
COPY . .

# Hot reload configuration
ENV HOST=0.0.0.0
ENV WDS_SOCKET_PORT=0
ENV CHOKIDAR_USEPOLLING=true
ENV FAST_REFRESH=true
ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

EXPOSE 3000
CMD ["npm", "start"]
