version: '3.8'

services:
  # Frontend development server with hot reload
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    command: npm start
    stdin_open: true
    tty: true

  # Backend development server with hot reload
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server:delegated
      - ./instance:/app/instance:delegated
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///instance/dev.db
      - JWT_SECRET_KEY=dev-secret-key
      - CORS_ORIGINS=http://localhost:3000
    command: flask --app server.app run --host=0.0.0.0 --port=5000 --debug --reload
    depends_on:
      - db

  # Development database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: becsmate_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: