version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      # Mount source code for development (comment out for production)
      - ./server:/app/server
      - ./client/build:/app/client/build
    command: >
      sh -c "cd /app && 
             python -m flask --app server.app run --host 0.0.0.0 --port 5000 --debug"
    
  # Development service for frontend
  frontend-dev:
    build:
      context: .
      target: frontend-build
    working_dir: /app/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: npm start
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    profiles:
      - dev

  # Production-like service
  app-prod:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    profiles:
      - prod